apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: coredns-deny-all-ingress
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: coredns
      tier: control-plane
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: coredns-deny-all-egress
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: coredns
      tier: control-plane
  policyTypes:
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: coredns-allow-dns-ingress-from-podcidr
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: coredns
      tier: control-plane
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: {{ .Values.coredns.podCIDR}}
    ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: coredns-allow-dns-ingress-from-nodeprivatecidr
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: coredns
      tier: control-plane
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: {{ .Values.coredns.nodePrivateCIDR}}
    ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: coredns-allow-healthcheck-ingress-from-control-plane-pods
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: coredns
      tier: control-plane
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          lokomotive.kinvolk.io/name: kube-system
      podSelector:
        matchExpressions:
        - {key: tier, operator: In, values: [node, control-plane]}
    ports:
    - port: 8080
      protocol: TCP
    - port: 8081
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: coredns-allow-metrics-ingress-from-selected-pods
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: coredns
      tier: control-plane
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          lokomotive.kinvolk.io/name: monitoring
    ports:
    - port: 9153
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: coredns-allow-egress-to-apiserver
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: coredns
      tier: control-plane
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          k8s-app: kube-apiserver
          tier: control-plane
    ports:
    - port: 6443
      protocol: TCP
    - port: 7443
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: coredns-allow-egress-to-dns-outside
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: coredns
      tier: control-plane
  policyTypes:
  - Egress
  egress:
  - to:
    ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP

