apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-hostendpoint-controller
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: calico-hostendpoint-controller
  name: calico-hostendpoint-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calico-hostendpoint-controller
  template:
    metadata:
      labels:
        app: calico-hostendpoint-controller
    spec:
      serviceAccountName: calico-hostendpoint-controller
      containers:
      - image: quay.io/kinvolk/calico-hostendpoint-controller:v0.0.1
        name: calico-hostendpoint-controller
        volumeMounts:
        - mountPath: /tmp/
          name: tmp-dir
      volumes:
      # mount in tmp so we can safely use from-scratch images and/or read-only containers
      - name: tmp-dir
        emptyDir: {}
