apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-egress-to-aws-metadata
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- else}}
  namespace: default
  {{- end }}
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 169.254.169.0/24
