apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ingress
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- else}}
  namespace: ingress
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress
subjects:
  - kind: ServiceAccount
    {{- if .Values.namespace }}
    namespace: {{ .Values.namespace }}
    {{- else}}
    namespace: ingress
    {{- end }}
    name: default
