# Adapted from https://raw.githubusercontent.com/openebs/openebs/master/k8s/demo/fio/demo-fio-cstor-sparse.yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: fio-cstor
  labels:
    name: fio-cstor
spec:
  containers:
  - resources:
      limits:
        cpu: 0.5
    name: fio-cstor
    image: openebs/tests-fio
    command: ["/bin/bash"]
    args: ["-c", "./fio_runner.sh --template file/basic-rw --size 256m --duration 36000; exit 0"]
    tty: true
    volumeMounts:
    - mountPath: /datadir
      name: datavol
  volumes:
    - name: datavol
      persistentVolumeClaim:
        claimName: fio-cstor-claim 
