apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: contour
  name: contour
  namespace: heptio-contour
spec:
  selector:
    matchLabels:
      app: contour
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: contour
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8002"
        # XXX: Modified manually to scrape envoy metrics on prometheus format
        prometheus.io/path: "/stats/prometheus"
        prometheus.io/format: "prometheus"
    spec:
      containers:
      # XXX: See the README for the reason to use a custom docker image
      - image: quay.io/kinvolk/contour:idle_timeout
        imagePullPolicy: Always
        name: contour
        command: ["contour"]
        args: ["serve", "--incluster", "--envoy-http-access-log", "/dev/null", "--envoy-https-access-log", "/dev/null"]

      # XXX: See the README for the reason to use envoy 1.10
      - image: docker.io/envoyproxy/envoy-alpine:v1.10.0
        name: envoy
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: https
        command: ["envoy"]
        args:
        - --config-path /config/contour.json
        - --service-cluster cluster0
        - --service-node node0
        - --log-level info
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8002
          initialDelaySeconds: 3
          periodSeconds: 3
        volumeMounts:
        - name: contour-config
          mountPath: /config
        lifecycle:
          preStop:
            exec:
              command: ["wget", "-qO-", "--post-data=''", "http://localhost:9001/healthcheck/fail"]
      initContainers:
      # XXX: See the README for the reason to use a custom docker image
      - image: quay.io/kinvolk/contour:idle_timeout
        imagePullPolicy: Always
        name: envoy-initconfig
        command: ["contour"]
        args: ["bootstrap", "/config/contour.json"]
        volumeMounts:
        - name: contour-config
          mountPath: /config
      volumes:
      - name: contour-config
        emptyDir: {}
      dnsPolicy: ClusterFirst
      serviceAccountName: contour
      terminationGracePeriodSeconds: 30
---
