apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- else}}
  namespace: cert-manager
  {{- end}}
  labels:
    app: cert-manager
    release: cert-manager
