apiVersion: v1
kind: Service
metadata:
  labels:
    app: contour
  name: contour-metrics
  namespace: heptio-contour
spec:
  ports:
  - port: 8000
    name: contour-metrics
  - port: 8002
    name: envoy-metrics
  selector:
    app: contour
