---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: envoy
  name: envoy
  namespace: projectcontour
spec:
  endpoints:
  - port: envoy-metrics
    path: /stats/prometheus
  namespaceSelector:
    matchNames:
    - projectcontour
  selector:
    matchLabels:
      app: envoy
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: contour
  name: contour
  namespace: projectcontour
spec:
  endpoints:
  - port: contour-metrics
    path: /metrics
  namespaceSelector:
    matchNames:
    - projectcontour
  selector:
    matchLabels:
      app: contour
---
